version: '3.1'
services:
  logsapp:
    container_name: logsttl
    depends_on:
      - mongo
    restart: always
    build: .
    ports:
      - 7000:4000
    networks:
      - app
    volumes:
     - .:/usr/app
    command: 'pm2-runtime start npm -- run start'
    
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: gdavila
      MONGO_INITDB_ROOT_PASSWORD: gdavilaadmin
      MONGO_INITDB_DATABASE: ttltest
    ports:
     - 27017:27017
    networks:
     - app
    volumes:
     - ./data/dump:/dump
networks:
  app:
    driver: "bridge"